[font]
normal = { family = 'JetBrainsMonoNL Nerd Font Mono', style = 'Regular' }
size = 15

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# custom hard background
background = '#17191A'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[keyboard]
bindings = [
    { key = "M", mods = "Control|Command", action = "ToggleMaximized" }
]

