#!/bin/bash

# zsh
ln -s $PWD/zsh/.zprofile ~/.zprofile
mkdir -pv ~/.cache/zsh
mkdir -pv ~/.config/zsh
ln -s $PWD/zsh/.zshrc ~/.config/zsh/.zshrc
if [ ! -d ~/.local/share/zsh/plugins/zsh-syntax-highlighting ]; then
    git clone git@github.com:zsh-users/zsh-syntax-highlighting.git ~/.local/share/zsh/zsh-syntax-highlighting
fi

# tmux
mkdir -p ~/.config/tmux/bin
touch ~/.config/tmux/projects
ln -s $PWD/tmux/.tmux.conf ~/.config/tmux/tmux.conf
ln -s $PWD/tmux/bin/tmux-sessionizer ~/.config/tmux/bin/tmux-sessionizer

# neovim
ln -s $PWD/nvim ~/.config

# idea
ln -s $PWD/idea/.ideavimrc ~/.ideavimrc

# kitty
ln -s $PWD/kitty ~/.config

# check if vscode-js-debug is already cloned
if [ ! -d ~/.local/share/nvim/mason/packages ]; then
  mkdir -p ~/.local/share/nvim/mason/packages
fi

if [ ! -d ~/.local/share/nvim/mason/packages/vscode-js-debug ]; then
    git clone https://github.com/microsoft/vscode-js-debug.git ~/.local/share/nvim/mason/packages/vscode-js-debug
    cd ~/.local/share/nvim/mason/packages/vscode-js-debug
    latestTag=$(git describe --tags "$(git rev-list --tags --max-count=1)")
    git checkout $latestTag

    # build to dist directory
    export NVM_DIR=~/.nvm
    source $(brew --prefix nvm)/nvm.sh # activate node

    npm install --legacy-peer-deps
    npx gulp vsDebugServerBundle
    mv dist out
fi
