#!/usr/bin/env bash

# macos
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 2

# zsh
ln -s $PWD/zsh/.zprofile ~/.zprofile
mkdir -pv ~/.cache/zsh
mkdir -pv ~/.config/zsh
ln -s $PWD/zsh/.zshrc ~/.config/zsh/.zshrc
if [ ! -d ~/.local/share/zsh/plugins/zsh-syntax-highlighting ]; then
    git clone git@github.com:zsh-users/zsh-syntax-highlighting.git ~/.local/share/zsh/plugins/zsh-syntax-highlighting
fi
if [ ! -d ~/.local/share/zsh/plugins/zsh-autosuggestions ]; then
    git clone git@github.com:zsh-users/zsh-autosuggestions.git ~/.local/share/zsh/plugins/zsh-autosuggestions
fi

# tmux
mkdir -p ~/.config/tmux/bin
touch ~/.config/tmux/projects
ln -s $PWD/tmux/tmux.conf ~/.config/tmux/tmux.conf
ln -s $PWD/tmux/bin/tmux-sessionizer ~/.config/tmux/bin/tmux-sessionizer

# neovim
ln -s $PWD/nvim ~/.config

# wezterm
ln -s $PWD/wezterm ~/.config

# alacritty
ln -s $PWD/alacritty ~/.config

# idea
ln -s $PWD/idea/.ideavimrc ~/.ideavimrc

# check if vscode-js-debug is already cloned
if [ ! -d ~/.local/share/nvim/mason/packages ]; then
  mkdir -p ~/.local/share/nvim/mason/packages
fi

# setup vscode-js-debug dap
if [ ! -d ~/.local/share/nvim/mason/packages/js-debug-dap ]; then
    # Use jq to extract both tag_name and browser_download_url in one go
    js_dap_version_and_url=$(curl -s https://api.github.com/repos/microsoft/vscode-js-debug/releases/latest | jq -r '
      .tag_name as $tag_name |
      .assets[] | select(.name | test("js-debug-dap-v")) | "\($tag_name) \(.browser_download_url)"
    ')

    js_dap_version=$(echo "$js_dap_version_and_url" | awk '{print $1}')
    js_dap_url=$(echo "$js_dap_version_and_url" | awk '{print $2}')

    curl -L -o ~/.local/share/nvim/mason/packages/js-debug-dap.tar.gz "$js_dap_url"
    mkdir -p ~/.local/share/nvim/mason/packages/js-debug-dap
    tar -xzf ~/.local/share/nvim/mason/packages/js-debug-dap.tar.gz -C ~/.local/share/nvim/mason/packages/js-debug-dap --strip-components=1
    rm ~/.local/share/nvim/mason/packages/js-debug-dap.tar.gz
    echo "js-debug-dap version $js_dap_version downloaded and extracted."
fi
