require("tjmadonna.plugins.telescope")
require("tjmadonna.plugins.lsp")
require("tjmadonna.plugins.copilot")
require("tjmadonna.plugins.dap")
require("tjmadonna.plugins.nvim-cmp")
require("tjmadonna.plugins.nvim-tree")
require("tjmadonna.plugins.toggleterm")
require("tjmadonna.plugins.treesitter")
