require("tjmadonna.options")
require("tjmadonna.keymaps")
require("tjmadonna.autocmds")

require("tjmadonna.lazy")
require("tjmadonna.gruvbox")
require("tjmadonna.bufferline")
require("tjmadonna.copilot")
require("tjmadonna.gitsigns")
require("tjmadonna.lualine")
require("tjmadonna.mason")
require("tjmadonna.neotest")
require("tjmadonna.nvim-cmp")
require("tjmadonna.nvim-tree")
require("tjmadonna.nvim-treesitter")
require("tjmadonna.nvim-web-devicons")
require("tjmadonna.rest-nvim")
require("tjmadonna.telescope")
